name: story_editor
description: "A Flutter image editor: Seamlessly enhance your images with user-friendly editing features."
version: 2.6.2
homepage: https://github.com/atsumo/story_editor/
repository: https://github.com/atsumo/story_editor/
issue_tracker: https://github.com/atsumo/story_editor/issues/
documentation: https://github.com/atsumo/story_editor/

topics:
  - image-editor
  - image
  - editor
  - widget
  - painting
  - story-editor
  - stamp

screenshots:
  - description: "Showcase from the story editor with the Whatsapp design"
    path: assets/showcase-whatsapp.png
  - description: "Showcase from the story editor with simple design"
    path: assets/showcase.png

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.2.2 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  image_editor: ^1.4.0
  extended_image: ^8.2.0
  rounded_background_text: ^0.5.0
  colorfilter_generator: ^0.0.8
  screenshot: ^2.3.0
  vibration: ^1.8.4
  http: ^1.2.1
  emoji_picker_flutter: ^2.1.1
  image: ^4.1.7
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  mockito: ^5.4.4
  network_image_mock: ^2.0.0
  build_runner: ^2.4.9
